issue/2910 Re-added missing _shouldStoreResponses=false behaviour
adaptlearning/adapt-contrib-spoor pull request #200
Opened 2020-09-15 11:38 UTC by oliverfoster

[#2910](https://github.com/adaptlearning/adapt_framework/issues/2910)

### Fixed
* Re-added behaviour which I accidentally removed whereby `_shouldStoreResponses: false` keeps `_isComplete` values

2020-09-21 11:19 UTC, cahirodoherty-learningpool approved these changes
👀

2020-09-21 16:41 UTC, moloko commented
OK I've just been giving this a bit of a test and have noticed a few things:

Using the OOTB course, if I complete all the components in co-05 and exit, then update the course to remove block b-05 (and its components) and add a new block/component at the end of co-05 (assigning that block a new `_trackingId`), then relaunch - I get a JavaScript error in the console and the course fails to restore the completion data of any content. Although courses built in the AAT have never been able to cope with this sort of update to a 'live course', courses built using the Framework have been able to handle this sort of change (so long as 'tracking ids' aren't 'recycled').

The setting `_shouldStoreAttempts` now doesn't appear to be implemented anywhere.

I thought that the original aim of this was to reduce suspend data usage but it actually seems to have increased usage... 

In Adapt v5.6.1 (with `_shouldStoreResponses` enabled so as to generate the maximum amount of data), there's 378 bytes of suspend data after I've completed everything:
<details>
<summary>Adapt v5.6.1 suspend data</summary>

`{"lang":"en","a11y":false,"captions":"en","completion":"11111111111101101111","questions":"AiE6IFhAcADgx4KAROiBYQIEA4MfCgSaogWECRAODHyZAAAQAAVogWECgAODHhIQCBOiBYQLEA4MXChGUogWEDRAODHw4MYUogWEDhAODHw4MQXogmIABABAA4MfCgIXogmIABEBAA4MfCgM","_isCourseComplete":false,"_isAssessmentPassed":true,"assessment":{"a-15":[1,1,4,4,0,{"c-100":true,"c-130":true,"c-110":true,"c-140":true}]}}`
</details>

In Adapt v5.7.0 (using the issue/2910 branch of spoor), it's 582 bytes of data...
<details>
<summary>Adapt v5.7.0 suspend data</summary>

`{"lang":"en","a11y":false,"c":"hMA","q":"oAPQ4XADAcATFAAOFwIwHAExQADhcQMBwBMUAA4XEjAcATFAAOFyAwHAExQADhcwNhwBMUNwDhdANhwBMUNwDhdQMBwBMUAA4XYDYcATFDcA4XcDccLgCOFEIGHC4AjgxCDhdyMBwBMUAA4WhAG44XEEeKGQYcLiCPDDIcLQkDccLiCPFB-YAAgAAGHC4gjwwfmAAIAADhaEkYDgCYoABwtCgNxwvQoQEcKHwRDDhehQgI4MPgiOFoWBqOFxBHig9ww4XEEeHuOFoYBgOFwBACgAHC0MIwHAEBQADhaGgbjhcQR4orAYcLiCPDFYHC0NIwHAExQADhaHAbjhcQR4oqAYcLiCPDFQHC0OIwHAExQADhaHgbjhcQR4ojAw4XEEeGIwcLQ8jAcATFAAOFogBuOFxBHiiIDDhcQR4YiBwtECMBwBMUAA4WiIGA4XAEAKAAcLREjAcAQFAAOFokBgOAJigAHC0TAwHAExQAA","captions":"en","a":{"a-15":"hReJkAomiEPhsOJBQoUK"}}`
</details>

2020-09-21 16:55 UTC, moloko commented
same test of suspend data following completion, this time with `_shouldStoreResponses: false` on both courses

<details>
<summary>Adapt v5.6.1 suspend data (233 bytes)</summary>

`{"lang":"en","a11y":false,"captions":"en","completion":"11111111111110111011","questions":"","_isCourseComplete":false,"_isAssessmentPassed":true,"assessment":{"a-15":[1,1,4,4,0,{"c-90":true,"c-110":true,"c-120":true,"c-130":true}]}}`
</details>


<details>
<summary>Adapt v5.7.0 suspend data (261 bytes)</summary>

`{"lang":"en","a11y":false,"captions":"en","c":"hMA","q":"oAPQoXABRQuBCihcQFFC4kKKFyAUULmAooXQBRQuoCihdgFFC7gKKF3IUULQgBRQtCQFFC0JIUULQoBRQtCwFFC0MAQULQwhBQtDQFFC0NIUULQ4BRQtDiFFC0PAUULQ8hRQtEAFFC0QIUULREBBQtESEFC0SAUULRMBQA","a":{"a-15":"hReJkAomhsPiEOJBQoUK"}}`
</details>

2020-09-21 17:10 UTC, moloko commented
and finally, just for completeness, the OOTB course with the assessment removed (and `_shouldStoreResponses: false`):

<details>
<summary>Adapt v5.6.1 suspend data (138 bytes)</summary>

`{"lang":"en","a11y":false,"captions":"en","completion":"111111111111","questions":"","_isCourseComplete":true,"_isAssessmentPassed":false}`
</details>


<details>
<summary>Adapt v5.7.0 suspend data (145 bytes)</summary>

`{"lang":"en","a11y":false,"captions":"en","c":"hIA","q":"oAIQoXABRQuBCihcQFFC4kKKFyAUULmAooXQBRQuoCihdgFFC7gKKF3IUULQgBRQtCQFFC0JIUULQoBRQtCwFA"}`
</details>

I was actually surprised to find that one had the least difference in storage size. I would have thought that the 'completion string' only needing to be 11 bytes for the 'binary' method of recording component completion would have made more of a difference - obviously the longer property names ('completion' vs 'c') has an impact but still, surprising.

2020-09-22 15:29 UTC, oliverfoster commented
> I thought that the original aim of this was to reduce suspend data usage but it actually seems to have increased usage...
> I was actually surprised to find that one had the least difference in storage size. I would have thought that the 'completion string' only needing to be 11 bytes for the 'binary' method of recording component completion would have made more of a difference - obviously the longer property names ('completion' vs 'c') has an impact but still, surprising.

With `_storeResponses: false` it's now storing the completion state, the tracking id and the component's relative offset from the `_trackingId` per component rather than per block. So it has a lot more information in one place than the binary completion string, this is to account for flexibility in the placement of trackingIds (moving from block to component).

5.7.0 with  `_storeResponses: true/false`  is now storing an additional array for the completion history of each question, it appears I accidentally removed the support for `_shouldStoreAttempts: false`, hence the inflated size over version 5.6.1 - I'm not sure what happened in that last big PR, I don't seem to have done a very good job in a few aspects.

2020-09-22 15:41 UTC, moloko commented
> I'm not sure what happened in that last [big PR](https://github.com/adaptlearning/adapt-contrib-spoor/pull/197), I don't seem to have done a very good job in a few aspects. It looks as though I was concentrating too hard on moving tracking to the components and forgot some of the other stuff I should have checked

Equally I should really have done all this sort of testing before releasing v5.7.0 - am kicking myself for not having done so!

2020-09-22 16:00 UTC, oliverfoster commented
Well. The good news is: it's going to be a lot easier to edit.

2020-09-22 17:12 UTC, moloko commented
cool, I shall re-test at some point tomorrow

2020-09-23 14:49 UTC, moloko approved these changes
lovely stuff - far as I can see all working now and seeing definite difference between having `_shouldStoreAttempts` enabled (587 bytes) and not (473 bytes)

no more error on changing the course structure either.

2020-09-23 14:56 UTC, moloko commented
in #194 you included some info about 'decoding' the tracking data... it would be really useful to have something like this - but which is accurate ;-) maybe as a Wiki page within the spoor repo?

2020-09-23 14:56 UTC, cahirodoherty-learningpool approved these changes
👀

2020-10-06 08:38 UTC, tomgreenfield requested changes

2020-10-06 08:38 UTC, tomgreenfield commented on js/serializers/ComponentSerializer.js
> +      if (shouldStoreAttempts || !shouldStoreResponses) {
Typo?
```suggestion
      if (shouldStoreAttempts && !shouldStoreResponses) {
```

2020-10-06 08:54 UTC, tomgreenfield approved these changes
:eye:

2020-10-06 08:56 UTC, moloko approved these changes

2020-10-06 09:09 UTC, merged